test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -100,11 +100,10 @@ jobs:
         shell: bash
         run: |
           FLUTTER_SDK_DIR=$(dirname $(dirname $(which flutter)))
-          PATCH_FILE="${{ github.workspace }}/rustdesk/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff"
+          PATCH_FILE="${{ github.workspace }}/self/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff"
           if [ -f "$PATCH_FILE" ]; then
-            cp "$PATCH_FILE" "$FLUTTER_SDK_DIR/"
             cd "$FLUTTER_SDK_DIR"
-            [[ "${{env.FLUTTER_VERSION}}" == "3.24.5" ]] && git apply "flutter_3.24.4_dropdown_menu_enableFilter.diff"
+            git apply "$PATCH_FILE" || echo "Warning: Flutter patch could not be applied. Continuing build."
             cd "${{ github.workspace }}/rustdesk"
           fi
           sed -i -e 's|2ded7f146437a761ffe6981e2f742038f85ca68d|08a471bb8ceccdd50483c81cdfa8b81b07b14b87|' ./flutter/pubspec.lock
@@ -130,17 +129,16 @@ jobs:
             sed -i '/<\/compatibility>/a \ \ \ \ \ \ \ \ <security>\n \ \ \ \ \ \ \ \ \ \ <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>\n \ \ \ \ \ \ \ \ </security>' ./flutter/windows/runner/runner.exe.manifest
           fi
           if [ "${{ env.CYCLE_MONITOR_FEATURE }}" == "true" ]; then
-            curl -s https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/cycle_monitor.diff -o cycle_monitor.diff && git apply cycle_monitor.diff
+            git apply "${{ github.workspace }}/self/.github/patches/cycle_monitor.diff"
           fi
           if [ "${{ env.X_OFFLINE_FEATURE }}" == "true" ]; then
-            curl -s https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/xoffline.diff -o xoffline.diff && git apply xoffline.diff
+            git apply "${{ github.workspace }}/self/.github/patches/xoffline.diff"
           fi
           if [ "${{ env.REMOVE_NEW_VERSION_NOTIF_FEATURE }}" == "true" ]; then
-            sed -i -e 's|updateUrl.isNotEmpty|false|' ./flutter/lib/desktop/pages/desktop_home_page.dart
-            sed -i '/let (request, url) =/,/Ok(())/{/Ok(())/!d}' ./src/common.rs
+            git apply "${{ github.workspace }}/self/.github/patches/removeNewVersionNotif.diff"
           fi
-          curl -s https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/allowCustom.diff -o allowCustom.diff && git apply allowCustom.diff
-          curl -s https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/removeSetupServerTip.diff -o removeSetupServerTip.diff && git apply removeSetupServerTip.diff
+          git apply "${{ github.workspace }}/self/.github/patches/allowCustom.diff"
+          git apply "${{ github.workspace }}/self/.github/patches/removeSetupServerTip.diff"
 
       - name: Apply Custom Branding (Icon, Logo, Server) and Build Icons
         working-directory: rustdesk
